//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Ordering.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sample.Ordering.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: 1,
        ///    &quot;BuyerId&quot;: 1,
        ///    &quot;Items&quot;: [
        ///      {
        ///        &quot;ProductName&quot;: &quot;Ausdom AW615 FullHD&quot;,
        ///        &quot;UnitPrice&quot;: 12.6,
        ///        &quot;Quantity&quot;: 3
        ///      },
        ///      {
        ///        &quot;ProductName&quot;: &quot;Trust SKETCH SILENT&quot;,
        ///        &quot;UnitPrice&quot;: 15.9,
        ///        &quot;Quantity&quot;: 1
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 2,
        ///    &quot;BuyerId&quot;: 2,
        ///    &quot;Items&quot;: [
        ///      {
        ///        &quot;ProductName&quot;: &quot;Ausdom AW615 FullHD&quot;,
        ///        &quot;UnitPrice&quot;: 12.6,
        ///        &quot;Quantity&quot;: 1
        ///      }
        ///    ]
        ///  },
        ///  {
        ///    &quot;Id&quot;: 3,
        ///    &quot;Bu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
    }
}
