//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sample.Users.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sample.Users.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: 1,
        ///    &quot;FirstName&quot;: &quot;Milan&quot;,
        ///    &quot;LastName&quot;: &quot;Battistini&quot;,
        ///    &quot;Address&quot;: &quot;2770 Daffodil Lane; Springfield&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: 2,
        ///    &quot;FirstName&quot;: &quot;Aaron&quot;,
        ///    &quot;LastName&quot;: &quot;Braulio&quot;,
        ///    &quot;Address&quot;: &quot;929 Laurel; Lee Eagan&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: 3,
        ///    &quot;FirstName&quot;: &quot;Brittanie&quot;,
        ///    &quot;LastName&quot;: &quot;Finkleisten&quot;,
        ///    &quot;Address&quot;: &quot;158 Cedar Street; El Dorado&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: 4,
        ///    &quot;FirstName&quot;: &quot;Debora&quot;,
        ///    &quot;LastName&quot;: &quot;Hoppenrath&quot;,
        ///    &quot;Address&quot;: &quot;4325 Hedge Street; Rochelle  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
